package org.limitless.phixeron.tools;

import io.aeron.archive.client.AeronArchive;
import io.aeron.archive.codecs.CatalogHeaderDecoder;
import io.aeron.archive.codecs.RecordingDescriptorDecoder;
import io.aeron.archive.codecs.RecordingDescriptorHeaderDecoder;
import io.aeron.archive.codecs.RecordingState;
import io.aeron.cluster.codecs.SessionMessageHeaderDecoder;
import io.aeron.logbuffer.FrameDescriptor;
import io.aeron.protocol.DataHeaderFlyweight;
import java.io.File;
import java.io.InputStream;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.agrona.BitUtil;
import org.agrona.concurrent.UnsafeBuffer;
import uk.co.real_logic.sbe.ir.Ir;
import uk.co.real_logic.sbe.ir.IrDecoder;
import uk.co.real_logic.sbe.ir.Token;
import uk.co.real_logic.sbe.json.JsonPrinter;
import uk.co.real_logic.sbe.otf.OtfHeaderDecoder;

/**
 * Offline dump of SBE messages recorded by Aeron Archive into an archive
 * directory (archive.catalog + segment files), printed as JSON using an
 * SBE IR (.sbeir) schema file.
 *
 * <p>The schemas generated by this build ship inside the jar as resources (see the {@code collectSbeIr}
 * Gradle task): {@code frame} (the envelope and core), {@code order}, {@code session} and
 * {@code basicdata} (the three application payloads), {@code unsequenced} (the node-local replay
 * control plane) and {@code cluster} (the Raft consensus log). All of them are loaded by default and each
 * frame is decoded against the schema its own header names — which is also how a payload inside an
 * envelope is decoded, so a schema is bundled here whether or not the Java side has codecs for it.
 * Naming one narrows the dump to it; an IR file outside the jar can be given instead.
 *
 * <p>By default, every valid recording in the catalog is dumped. A node restart mints a <em>new</em>
 * tap recording rather than extending the old one, so the default output repeats history. Pass a
 * stream id to select instead; see {@link #scanAndDumpLog()}.
 */
public class SbeLogPrinter {
    /** Bundled schema names, in the order {@code --list-schemas} prints them. */
    private static final String[] BUNDLED_SCHEMAS =
        {"frame", "order", "session", "basicdata", "unsequenced", "cluster"};
    private static final int CATALOG_HEADER_LENGTH = CatalogHeaderDecoder.BLOCK_LENGTH;
    private static final int DESCRIPTOR_HEADER_LENGTH = RecordingDescriptorHeaderDecoder.BLOCK_LENGTH;

    /** streamIdFilter value meaning "no filter" — dump every recording. Stream id 0 is legal, so 0 cannot serve. */
    public static final int NO_STREAM_FILTER = Integer.MIN_VALUE;

    private static final String RECORDING_SEGMENT_SUFFIX = ".rec";

    /** The frame layer's schema id, whose two templates carry every other protocol's messages. */
    private static final int FRAME_SCHEMA_ID = org.limitless.phixeron.sbe.frame.MessageHeaderDecoder.SCHEMA_ID;

    /** {@code varDataEncoding}'s length prefix, between the frame's block and its payload. */
    private static final int PAYLOAD_PREFIX_LENGTH =
        org.limitless.phixeron.sbe.frame.SequencedDecoder.payloadHeaderLength();

    /** One loaded schema: its IR (for template lookup) and the printer built from it. */
    private record Schema(Ir ir, JsonPrinter printer) {
    }

    private final File archiveDir;
    private final Map<Integer, Schema> schemasBySchemaId = new HashMap<>();

    private final OtfHeaderDecoder sbeHeaderDecoder;
    private final DataHeaderFlyweight dataHeader;
        private final RecordingDescriptorHeaderDecoder headerDecoder = new RecordingDescriptorHeaderDecoder();
    private final RecordingDescriptorDecoder descriptorDecoder = new RecordingDescriptorDecoder();

    private final int streamIdFilter;
    private final boolean oneLine;
    private final StringBuilder builder = new StringBuilder();

    public SbeLogPrinter(final List<Ir> irs, final String archiveDirPath, final int streamIdFilter,
                         final boolean oneLine) {
        this.archiveDir = new File(archiveDirPath);
        if (!archiveDir.exists() || !archiveDir.isDirectory()) {
            throw new IllegalArgumentException("Invalid archive directory: " + archiveDirPath);
        }
        this.streamIdFilter = streamIdFilter;
        this.oneLine = oneLine;
        for (final Ir loaded : irs) {
            schemasBySchemaId.put(loaded.id(), new Schema(loaded, new JsonPrinter(loaded)));
        }
        // Every schema here uses the standard messageHeader composite, so any one of them reads the
        // schema id that selects the rest.
        this.sbeHeaderDecoder = new OtfHeaderDecoder(irs.getFirst().headerStructure());
        this.dataHeader = new DataHeaderFlyweight();
    }

    /** Loads one of the IR files packaged in the jar, by schema name. */
    private static Ir loadBundledIr(final String schema) throws Exception {
        try (InputStream in = SbeLogPrinter.class.getResourceAsStream("sbeir/sbe-" + schema + ".sbeir")) {
            if (null == in) {
                throw new IllegalArgumentException("Unknown schema '" + schema + "' — bundled: " +
                                                   String.join(", ", BUNDLED_SCHEMAS));
            }
            try (IrDecoder irDecoder = new IrDecoder(ByteBuffer.wrap(in.readAllBytes()))) {
                return irDecoder.decode();
            }
        }
    }

    private static List<Ir> loadAllBundledIrs() throws Exception {
        final List<Ir> irs = new ArrayList<>(BUNDLED_SCHEMAS.length);
        for (final String schema : BUNDLED_SCHEMAS) {
            irs.add(loadBundledIr(schema));
        }
        return irs;
    }

    private static Ir loadIrFile(final String specIrPath) {
        try (IrDecoder irDecoder = new IrDecoder(specIrPath)) {
            return irDecoder.decode();
        }
    }

    /**
     * Message name for a template id, for labelling the dump — a header-only message such as {@code ClusterHeartbeat}
     * is otherwise indistinguishable from any other in the JSON, which carries field values only. The first
     * token of a message is its BEGIN_MESSAGE token, whose name is the message name.
     * @param ir internal representation
     * @param templateId template identity
     * @return message name
     */
    private static String messageName(final Ir ir, final int templateId) {
        final List<Token> tokens = ir.getMessage(templateId);
        return null == tokens || tokens.isEmpty() ? "<unknown>" : tokens.getFirst().name();
    }

    /**
     * Message token
     * @param ir internal representation
     * @param templateId message templateId
     * @return token
     */
    private static Token messageToken(final Ir ir, final int templateId) {
        final List<Token> tokens = ir.getMessage(templateId);
        return null == tokens || tokens.isEmpty() ? null : tokens.getFirst();
    }

    /**
     * A cluster-log {@code SessionMessageHeader} is not a standalone entry: {@code LogPublisher} appends
     * the raw client ingress payload — a self-describing SBE message in a different schema — immediately
     * after it in the same Aeron frame (this is what {@code ClusterStreamSender::send} builds). Without
     * this, the dump shows only the envelope and silently drops the message it wrapped.
     * @param schema protocol schema
     * @param templateId message templateIdn
     * @param buffer message buffer
     * @param payloadOffset payload offset
     * @param frameEndOffset frame end offset
     */
    private void appendNestedIngressMessage(final Schema schema,
                                            final int templateId,
                                            final UnsafeBuffer buffer,
                                            final int payloadOffset,
                                            final int frameEndOffset) {
        final Ir ir = schema.ir();
        final Token message = messageToken(ir, templateId);
        if (null == message) {
            return;
        }
        if (SessionMessageHeaderDecoder.SCHEMA_ID == ir.id() &&
            SessionMessageHeaderDecoder.TEMPLATE_ID == message.id()) {
            appendNested(buffer, payloadOffset + sbeHeaderDecoder.encodedLength() +
                                 sbeHeaderDecoder.getBlockLength(buffer, payloadOffset), frameEndOffset);
            return;
        }
        if (FRAME_SCHEMA_ID == ir.id()) {
            // The seqeron envelope: the message is one length-prefixed payload past the frame's block, and
            // the frame line alone would say only that a frame went by, never what it carried.
            appendNested(buffer, payloadOffset + sbeHeaderDecoder.encodedLength() +
                                 sbeHeaderDecoder.getBlockLength(buffer, payloadOffset) + PAYLOAD_PREFIX_LENGTH,
                         frameEndOffset);
        }
    }

    /**
     * Prints the message at {@code nestedOffset} beside the frame that carried it, on the same line.
     *
     * <p>A payload seqeron does not own prints as its schema and template ids rather than being decoded —
     * the printer holds no descriptor for it, and guessing one would read a foreign schema's numbering as
     * a known schema's (doc/seqeron-protocol-spec.md §13.1).
     */
    private void appendNested(final UnsafeBuffer buffer, final int nestedOffset, final int frameEndOffset) {
        if (nestedOffset >= frameEndOffset) {
            return;
        }
        final int nestedSchemaId = sbeHeaderDecoder.getSchemaId(buffer, nestedOffset);
        final int nestedTemplateId = sbeHeaderDecoder.getTemplateId(buffer, nestedOffset);
        final Schema nestedSchema = schemasBySchemaId.get(nestedSchemaId);
        builder.append(' ');
        if (null == nestedSchema || null == nestedSchema.ir().getMessage(nestedTemplateId)) {
            builder.append("<undecodable ingress payload: schema ").append(nestedSchemaId)
                .append(", templateId ").append(nestedTemplateId).append('>');
            return;
        }
        builder.append(messageName(nestedSchema.ir(), nestedTemplateId)).append('=');
        nestedSchema.printer().print(builder, buffer, nestedOffset);
    }

    /**
     * Collapses the pretty-printed JSON onto a single line.
     * @param builder string builder
     */
    private static void collapse(final StringBuilder builder) {
        int position = 0;
        for (int read = 0, length = builder.length(); read < length; read++) {
            final char c = builder.charAt(read);
            if ('\n' == c) {
                while (read + 1 < length && ' ' == builder.charAt(read + 1)) {
                    ++read;
                }
                if (position > 0 && ' ' != builder.charAt(position - 1)) {
                    builder.setCharAt(position, ' ');
                    ++position;
                }
            } else {
                builder.setCharAt(position, c);
                ++position;
            }
        }
        if (position > 0 && ' ' == builder.charAt(position - 1)) {
            --position;
        }
        builder.setLength(position);
    }

    /**
     * Dumps recordings as JSON.
     * @return true if at least one recording was dumped.
     */
    public boolean scanAndDumpLog() {
        final File catalogFile = new File(archiveDir, "archive.catalog");
        if (!catalogFile.exists()) {
            System.err.println("Could not locate archive.catalog file in " + archiveDir);
            return false;
        }
        try (RandomAccessFile file = new RandomAccessFile(catalogFile, "r"); FileChannel channel = file.getChannel()) {
            final long fileLength = channel.size();
            final ByteBuffer byteBuffer = channel.map(FileChannel.MapMode.READ_ONLY, 0, fileLength);
            final UnsafeBuffer catalogBuffer = new UnsafeBuffer(byteBuffer);
            processFile(fileLength, catalogBuffer);
        } catch (Exception error) {
            System.err.println("Failed parsing catalog file: " + error.getMessage());
            return false;
        }
        return true;
    }

    private void processFile(final long fileLength, final UnsafeBuffer buffer) {
        int offset = CATALOG_HEADER_LENGTH;
        int selectedOffset = -1;
        long selectedRecordingId = -1;
        int recordingLength = 1;
        boolean found = false;
        while (recordingLength >= 1 && offset + DESCRIPTOR_HEADER_LENGTH <= fileLength) {
            headerDecoder.wrap(buffer, offset, RecordingDescriptorHeaderDecoder.BLOCK_LENGTH,
                RecordingDescriptorHeaderDecoder.SCHEMA_VERSION);
            recordingLength = headerDecoder.length();
            if (recordingLength >= 1) {
                final int frameLength = BitUtil.align(recordingLength + DESCRIPTOR_HEADER_LENGTH,
                    BitUtil.CACHE_LINE_LENGTH);
                if (headerDecoder.state() == RecordingState.VALID) {
                    final int descriptorOffset = offset + DESCRIPTOR_HEADER_LENGTH;
                    descriptorDecoder.wrap(buffer, descriptorOffset,
                        RecordingDescriptorDecoder.BLOCK_LENGTH,
                        RecordingDescriptorDecoder.SCHEMA_VERSION);
                    if (NO_STREAM_FILTER == streamIdFilter) {
                        dumpRecording(descriptorDecoder);
                        found = true;
                    } else if (descriptorDecoder.streamId() == streamIdFilter &&
                        descriptorDecoder.recordingId() > selectedRecordingId) {
                        selectedRecordingId = descriptorDecoder.recordingId();
                        selectedOffset = descriptorOffset;
                    }
                }
                offset += frameLength;
            }
        }
        if (NO_STREAM_FILTER != streamIdFilter && selectedOffset >= 0) {
            descriptorDecoder.wrap(buffer, selectedOffset, RecordingDescriptorDecoder.BLOCK_LENGTH,
                RecordingDescriptorDecoder.SCHEMA_VERSION);
            dumpRecording(descriptorDecoder);
            found = true;
        }
        if (!found) {
            System.err.println(NO_STREAM_FILTER == streamIdFilter ?
                "No valid recordings found in catalog." :
                "No valid recording on stream " + streamIdFilter + " found in catalog.");
        }
    }

    private void dumpRecording(final RecordingDescriptorDecoder descriptorDecoder) {
        final long recordingId = descriptorDecoder.recordingId();
        final long startPosition = descriptorDecoder.startPosition();
        final long stopPosition = descriptorDecoder.stopPosition();
        final int termBufferLength = descriptorDecoder.termBufferLength();
        final int segmentFileLength = descriptorDecoder.segmentFileLength();
        System.out.printf("[Catalog] Recording ID: %d | Stream ID: %d | Start Pos: %d | Stop Pos: %d%n", recordingId,
                          descriptorDecoder.streamId(), startPosition, stopPosition);
        readPhysicalSegments(recordingId, startPosition, stopPosition, termBufferLength, segmentFileLength);
    }

    /**
     * Read log segment
     * @param recordingId recording identity
     * @param startPos start position
     * @param stopPos stop position
     * @param termLength term buffer length
     * @param segmentLength segment length
     */
    private void readPhysicalSegments(final long recordingId,
                                      final long startPos,
                                      final long stopPos,
                                      final int termLength,
                                      final int segmentLength) {
        // An in-progress recording has no stop position yet; rely on frame/segment EOF to end the scan.
        final long endPosition = stopPos == AeronArchive.NULL_POSITION ? Long.MAX_VALUE : stopPos;
        for (long position = startPos; position < endPosition; ) {
            // The segment grid is anchored on the recording's start term, not on position 0.
            final long segmentBasePosition = AeronArchive.segmentFileBasePosition(startPos, position, termLength,
                                                                                 segmentLength);
            final File segmentFile = new File(archiveDir, recordingId + "-" + segmentBasePosition +
                RECORDING_SEGMENT_SUFFIX);
            if (!segmentFile.exists()) {
                break;
            }
            try (RandomAccessFile raf = new RandomAccessFile(segmentFile, "r");
                 FileChannel channel = raf.getChannel()) {
                final long fileLength = channel.size();
                final ByteBuffer mappedFile = channel.map(FileChannel.MapMode.READ_ONLY, 0, fileLength);
                final UnsafeBuffer buffer = new UnsafeBuffer(mappedFile);
                int fileOffset = (int)(position - segmentBasePosition);
                while (fileOffset + DataHeaderFlyweight.HEADER_LENGTH <= fileLength && position < endPosition) {
                    dataHeader.wrap(buffer, fileOffset, (int)fileLength - fileOffset);
                    final int frameLength = printMessage(fileOffset, position, buffer);
                    if (frameLength <= 0) {
                        // Zero-filled tail: the end of a still-growing recording.
                        return;
                    }
                    final int paddedLength = BitUtil.align(frameLength, FrameDescriptor.FRAME_ALIGNMENT);
                    fileOffset += paddedLength;
                    position += paddedLength;
                }
            } catch (Exception error) {
                System.err.println("Exception parsing segment " + segmentFile + ": " + error.getMessage());
                break;
            }
        }
    }

    private int printMessage(final int fileOffset, final long currentPosition, final UnsafeBuffer buffer) {
        final int frameLength = dataHeader.frameLength();
        if (frameLength >= 1 && dataHeader.headerType() == DataHeaderFlyweight.HDR_TYPE_DATA) {
            final int sbePayloadOffset = fileOffset + DataHeaderFlyweight.HEADER_LENGTH;
            final int templateId = sbeHeaderDecoder.getTemplateId(buffer, sbePayloadOffset);
            final int schemaId = sbeHeaderDecoder.getSchemaId(buffer, sbePayloadOffset);
            final Schema schema = schemasBySchemaId.get(schemaId);
            if (null == schema) {
                System.out.format("Position: %d, Error: Schema %d not loaded, templateId = %d\n",
                    currentPosition, schemaId, templateId);
            } else {
                final Ir ir = schema.ir();
                if (null == ir.getMessage(templateId)) {
                    System.out.format("Position: %d, Error: templpateId = %d not in schema\n",
                        currentPosition, templateId);
                } else {
                    builder.setLength(0);
                    builder.append(messageName(ir, templateId)).append(" = ");
                    schema.printer().print(builder, buffer, sbePayloadOffset);
                    appendNestedIngressMessage(schema, templateId, buffer, sbePayloadOffset,
                        fileOffset + frameLength);
                    if (oneLine) {
                        collapse(builder);
                    }
                    System.out.println(builder);
                }
            }
        }
        return frameLength;
    }

    private static void usage() {
        System.out.println("Usage: sbe-log-printer.sh [--schema <name>|--spec <file.sbeir>] <archive-dir> " +
                           "[--stream <id>] [--oneline]");
        System.out.println("  --schema <name>  decode only this bundled schema (default: all of " +
                           String.join(", ", BUNDLED_SCHEMAS) + ", each frame matched on its schema id)");
        System.out.println("  --spec <file>    decode against an IR file outside the jar instead");
        System.out.println("  --stream <id>    dump only the newest recording on that stream");
        System.out.println("  --oneline        print each message as a single line of JSON");
        System.out.println("  --list-schemas   list the bundled schema names and exit");
    }

    public static void main(String[] args) {
        String schema = null;
        String specIrPath = null;
        String archiveDirPath = null;
        int streamIdFilter = NO_STREAM_FILTER;
        boolean oneLine = false;

        for (int i = 0; i < args.length; i++) {
            if ("--oneline".equals(args[i])) {
                oneLine = true;
            } else if ("--list-schemas".equals(args[i])) {
                for (final String name : BUNDLED_SCHEMAS) {
                    System.out.println(name);
                }
                return;
            } else if ("--stream".equals(args[i]) || "--schema".equals(args[i]) || "--spec".equals(args[i])) {
                final String option = args[i];
                if (++i == args.length) {
                    System.err.println("Missing value for " + option);
                    usage();
                    System.exit(1);
                }
                switch (option) {
                    case "--schema" -> schema = args[i];
                    case "--spec" -> specIrPath = args[i];
                    default -> {
                        try {
                            streamIdFilter = Integer.parseInt(args[i]);
                        } catch (NumberFormatException e) {
                            System.err.println("Not a stream id: " + args[i]);
                            System.exit(1);
                        }
                    }
                }
            } else if (archiveDirPath == null) {
                archiveDirPath = args[i];
            } else {
                System.err.println("Unexpected argument: " + args[i]);
                usage();
                System.exit(1);
            }
        }

        if (archiveDirPath == null) {
            usage();
            System.exit(1);
        }
        if (schema != null && specIrPath != null) {
            System.err.println("--schema and --spec are mutually exclusive");
            System.exit(1);
        }
        // A typo here is a usage error, so report it as one rather than as a stack trace from the load below.
        if (schema != null && !List.of(BUNDLED_SCHEMAS).contains(schema)) {
            System.err.println("Unknown schema '" + schema + "' — bundled: " + String.join(", ", BUNDLED_SCHEMAS));
            System.exit(1);
        }
        try {
            final List<Ir> irs = specIrPath != null ? List.of(loadIrFile(specIrPath))
                                     : schema != null ? List.of(loadBundledIr(schema))
                                         : loadAllBundledIrs();
            final SbeLogPrinter printer = new SbeLogPrinter(irs, archiveDirPath, streamIdFilter, oneLine);
            if (!printer.scanAndDumpLog()) {
                System.exit(1);
            }
        } catch (Exception e) {
            System.err.println("Execution failed: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
